### ISSUE TITLE
Demo data is part of bundles

### ISSUE THREAD

**Issue by sadortun** [DigitalState/Platform-Application#2]
Hi @mario-digitalstate 

Many bundles include Demo data as part of the bundles. Often they have references to other bundles. I think they should be part of the main applicaiton.

For example:
- [ ] Platform-User-Persona-Bundle/Migrations/Data/ORM/LoadPersonaData.php
- [ ] Platform-User-Bundle/Migrations/Data/ORM/LoadRoleData.php

I would recommend that you put them in a `DemoBundle` as Oro did https://github.com/orocrm/crm/tree/master/src/Oro/Bundle/DemoDataBundle

Thanks,
Samuel

**Comment by mario-digitalstate** [comment]
Completed.
